apiVersion: v1
kind: Namespace
metadata:
  name: grafana-dev
  labels:
    name: grafana-dev
---
apiVersion: v1
kind: Pod
metadata:
  labels:
    app: grafana
  name: grafana
  namespace: grafana-dev 
spec:
  containers:
  - name: grafana
    image: grafana/grafana:latest
    volumeMounts:
  nodeSelector:
    kubernetes.io/hostname: crc
