apiVersion: v1
kind: Namespace
metadata:
  name: prometheus-dev
  labels:
    name: prometheus-dev
---
apiVersion: v1
kind: Pod
metadata:
  labels:
    app: prometheus
  name: prometheus
  namespace: prometheus-dev 
spec:
  containers:
  - name: prometheus
    image: prom/prometheus:latest
    volumeMounts:
  nodeSelector:
    kubernetes.io/hostname: crc
